#!/bin/sh

### BEGIN INIT INFO
# Provides:        hotpi-baker
# Required-Start:  $network $syslog
# Required-Stop:   $network $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    1
# Short-Description: Start HotPi Baker daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

DAEMON=/usr/sbin/hotpi-baker
PIDFILE=/var/run/hotpi-baker.pid

test -x $DAEMON || exit 5

case $1 in
    start)
        log_daemon_msg "Starting HotPi Baker" "hotpi-baker"
        if [ ! -f "/etc/hotpi/baker.conf" ]; then
            log_failure_msg "Please create /etc/hotpi/baker.conf first!"
            exit 1
        fi
        start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON
        status=$?
        log_end_msg $status
        ;;
    stop)
        log_daemon_msg "Stopping HotPi Baker" "hotpi-baker"
        start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
        log_end_msg $?
        rm -f $PIDFILE
        ;;
    restart|force-reload)
        $0 stop && sleep 2 && $0 start
        ;;
    try-restart)
        if $0 status >/dev/null; then
            $0 restart
        else
            exit 0
        fi
        ;;
    reload)
        exit 3
        ;;
    status)
        status_of_proc $DAEMON "HotPi Baker"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
        exit 2
        ;;
esac
